### ISSUE TITLE
TNH is empty

### ISSUE THREAD

**Issue by colegmr** [devyndamonster/TakeAndHoldTweaker#93]
Ever since the new update TNH rounds are just empty maps no sosigs or holds
and Ive narrowed the cause down to this mod
upon reverting to the last version the problem is resolved

**Comment by devyndamonster** [comment]
Sorry for the inconvenience, the latest update is only compatible with the alpha branch of H3VR because it was broken there. For playing with mods on the current main branch you should use the previous version of TNH Tweaker. I made an announcement in the modding discord but forgot to announce it here. Hope this helps
