### ISSUE TITLE
Bug:  Version 1.7.5 TNH maps are now empty

### ISSUE THREAD

**Issue by colegmr** [devyndamonster/TakeAndHoldTweaker#94]
Ever since the latest update TNH rounds no longer spawn sosigs or holds
the maps are empty as is the radar 
reverting to 1.7.4 fixes this

-thanks for your hard work
also cool umami avatar looks like the soup guy

**Comment by DesiQuintans** [comment]
The relevant log output for this is:

```
[Error  : Unity Log] Can't remove TNH_SupplyPoint (Script) because ForcedSpawn (Script) depends on it
[Error  : Unity Log] MissingMethodException: Method not found: 'FistVR.Sosig.SetIFF'.
Stack trace:
TNHTweaker.Patches.PatrolPatches.SpawnEnemy (TNHTweaker.ObjectTemplates.SosigTemplate template, TNHTweaker.ObjectTemplates.CustomCharacter character, UnityEngine.Transform spawnLocation, TNHModifier_AIDifficulty difficulty, Int32 IFF, Boolean isAssault, Vector3 pointOfInterest, Boolean allowAllWeapons)
TNHTweaker.Patches.TNHPatches.SpawnTakeGroupReplacement (System.Collections.Generic.List`1 ___SpawnPoints_Sosigs_Defense, FistVR.TNH_TakeChallenge ___T, FistVR.TNH_Manager ___M, System.Collections.Generic.List`1 ___m_activeSosigs)
(wrapper dynamic-method) FistVR.TNH_HoldPoint:DMD<FistVR.TNH_HoldPoint::SpawnTakeEnemyGroup> (FistVR.TNH_HoldPoint)
```

**Comment by devyndamonster** [comment]
Oh I already closed the ticket you made for this bug colegmr. I'll copy my response from the previous post you made I guess:

Sorry for the inconvenience, the latest update is only compatible with the alpha branch of H3VR because it was broken there. For playing with mods on the current main branch you should use the previous version of TNH Tweaker. I made an announcement in the modding discord but forgot to announce it here. Hope this helps

From here: https://github.com/devyndamonster/TakeAndHoldTweaker/issues/93#issuecomment-1079954954

**Comment by colegmr** [comment]
Thanks for the reply 
sorry i didn't notice you closed the branch
glad to know using the older version shouldn't cause problems
